### ISSUE TITLE
for next version add Below Detection Limits pre- and post- 2012

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-nutrient#3]

**Comment by ecrockford** [comment]
Current detection limits 
ammonium <0.015
silicate <0.03
Phosphate <0.009
Nitrate + Nitrite <0.04

Prior to sample ID N_1471 ALL detection limits were <0.05

**Comment by ecrockford** [comment]
<0.05 prior to April 2012. Nutrient specific DL the same since then. Added to analysis methods section.
